### ISSUE TITLE
Review checklist

### ISSUE THREAD

**Issue by davanstrien** [LibraryCarpentry/lc-machine-learning#43]
A horribly messy list of things to check for during the review

## Broad lesson structure stuff
- [ ] An overview of the lifecycle. Do we want something like/or a link to this: https://xd.adobe.com/view/aff836b9-aea6-4ee2-9fc5-891e0ac30efc-faab/screen/d5767149-67ee-46bf-93cf-b2f4d9e74d21?fullscreen. If so where does it best sit

## Lesson content
- [ ] Check for overlaps in content between episodes 
- [ ] Glossary terms things to add as a term and things we need to add to glossary first (maybe add to issue https://github.com/carpentries-incubator/machine-learning-librarians-archivists/issues/40)
- [ ] Content suggestions / missing or things that are surplus
- [ ]  Do we have enough exercises and the right kind?

## Detailed comments
- [ ] Grammar/spelling (maybe make changes directly in the pull request/inline.

## Lesson formatting  
- [ ] Any suggestions for time for each lesson 
- [ ] Recommend Reading /vs citations how much do we want to cover and do we want to recommend some key readings for each lesson?

**Comment by davanstrien** [comment]
@MikeTrizna @mark-bell-tna @noramcgregor feel free to make suggestions changes to this
